version: '3.6'
services:
  postgres:
    image: postgres:11.5
    restart: unless-stopped
    volumes:
      - ./docker-data/postgresql:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - '${POSTGRES_PORT}:5432'
